# Generated by Django 4.0.7 on 2022-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('Type', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Furnace_Poreclains',
            fields=[
                ('Poreclain', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Furnace_Press',
            fields=[
                ('Press', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Furnace_Sintering',
            fields=[
                ('Sintering', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('Type', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('Type', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MZ_Machine',
            fields=[
                ('MachineType', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MZ_Zircon',
            fields=[
                ('ZirconType', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('Type', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('IOR', models.CharField(max_length=5000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suction',
            fields=[
                ('Type', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
    ]
