# Generated by Django 4.0.7 on 2022-08-14 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('SalesmanRep', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PRE', models.CharField(blank=True, max_length=50)),
                ('Name', models.CharField(max_length=500)),
                ('Rank', models.CharField(blank=True, max_length=50)),
                ('Phone', models.CharField(blank=True, max_length=50)),
                ('Jan', models.CharField(blank=True, max_length=500)),
                ('Feb', models.CharField(blank=True, max_length=500)),
                ('Mar', models.CharField(blank=True, max_length=500)),
                ('Apr', models.CharField(blank=True, max_length=500)),
                ('May', models.CharField(blank=True, max_length=500)),
                ('June', models.CharField(blank=True, max_length=500)),
                ('July', models.CharField(blank=True, max_length=500)),
                ('Aug', models.CharField(blank=True, max_length=500)),
                ('Sep', models.CharField(blank=True, max_length=500)),
                ('Oct', models.CharField(blank=True, max_length=500)),
                ('Nov', models.CharField(blank=True, max_length=500)),
                ('Dec', models.CharField(blank=True, max_length=500)),
                ('Location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='salesmen.area')),
                ('Salesman', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Details', models.CharField(max_length=999999)),
                ('Salesman', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Mz_Price', models.CharField(blank=True, max_length=999999)),
                ('Mz_AvgMonths', models.CharField(blank=True, max_length=999999)),
                ('Scanner_Price', models.CharField(blank=True, max_length=999999)),
                ('Scanner_Labscanner', models.CharField(blank=True, max_length=999999)),
                ('Suction_Price', models.CharField(blank=True, max_length=999999)),
                ('Comp_Price', models.CharField(blank=True, max_length=999999)),
                ('Comp_Gram', models.CharField(blank=True, max_length=999999)),
                ('Powder_Price', models.CharField(blank=True, max_length=999999)),
                ('Powder_Gram', models.CharField(blank=True, max_length=999999)),
                ('Metal_Price', models.CharField(blank=True, max_length=999999)),
                ('Metal_Gram', models.CharField(blank=True, max_length=999999)),
                ('Investment_Price', models.CharField(blank=True, max_length=999999)),
                ('Investment_AvgMonths', models.CharField(blank=True, max_length=999999)),
                ('Date', models.CharField(blank=True, max_length=999999)),
                ('Notes', models.CharField(blank=True, max_length=999999)),
                ('NextAct', models.CharField(blank=True, max_length=9999999)),
                ('Area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='salesmen.area')),
                ('Comp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.composite')),
                ('Customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='salesmen.customer')),
                ('Furnace_Poreclains', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.furnace_poreclains')),
                ('Furnace_Press', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.furnace_press')),
                ('Furnace_Sintering', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.furnace_sintering')),
                ('Investment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.investment')),
                ('MZ_Machine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.mz_machine')),
                ('MZ_Zircon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.mz_zircon')),
                ('Metal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.metal')),
                ('Powder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.powder')),
                ('Salesman', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Scanner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.scanner')),
                ('Suction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.suction')),
            ],
        ),
    ]
