# Generated by Django 4.0.7 on 2022-08-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='Id',
        ),
        migrations.AddField(
            model_name='salesman',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
